chore: updated makefile to install java

diff --git a/benchmark/Makefile b/benchmark/Makefile
--- a/benchmark/Makefile
+++ b/benchmark/Makefile
@@ -4,6 +4,15 @@ setup:
 		echo "❌ pyenv is not installed or not on PATH."; \
 		exit 1; \
 	fi; \
+	# Install Java if not installed \
+	if ! command -v java >/dev/null 2>&1; then \
+		echo "Java not found. Installing OpenJDK 17..."; \
+		sudo apt update && sudo apt install -y openjdk-17-jdk; \
+	else \
+		echo "Java found."; \
+	fi; \
+	export JAVA_HOME=$$(readlink -f $$(which java) | sed "s:bin/java::"); \
+	echo "JAVA_HOME is set to $$JAVA_HOME"; \
 	pyenv install -s $$(cat .python-version); \
 	PYENV_PYTHON=$$(pyenv which python); \
 	$$PYENV_PYTHON -m venv .venv && \
